version: '3.8'
services:
  myapp: 
    image: usermanagement:latest
    ports:
      - 3000:3000
    deploy:
      replicas: 3
  sitetwo: 
    image: usermanagement:latest
    ports:
      - 3001:3000
    deploy:
      replicas: 2
  